name: Clojure CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 8
          
    - name: Install dependencies
      run: lein deps
      
    - name: Gen proto
      run: lein protodeps generate
      
    - name: Uberjar
      run: lein uberjar

    - name: Set enviroment for github-release
      run: |
        echo RELEASE_TAG="$(grep -m1 'defproject' project.clj | awk '{print $3}' | tr -d '\"')" >> "$GITHUB_ENV"
        echo RELEASE_NAME="$GITHUB_WORKFLOW" >> "$GITHUB_ENV"

    - name: Create a Release
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.RELEASE_TAG }}
        files: target/profedit.jar
        allow_override: true
