name: Clojure CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        architecture: x64
        java-package: jdk
        java-version: 20

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@11.0
      with:
        lein: 2.10.0
    - name: Install dependencies
      run: lein deps

    - name: Gen proto
      run: lein protodeps generate

    - name: Uberjar
      run: lein uberjar

    - name: Create Windows executable
      run: |
        tar -xzf .github/workflows/launch4j-3.13-linux-x64.tgz
        chmod +x launch4j/launch4j
        launch4j/launch4j .github/workflows/build.xml
        wget -q https://cdn.azul.com/zulu/bin/zulu20.30.11-ca-jre20.0.1-win_x64.zip
        unzip zulu20.30.11-ca-jre20.0.1-win_x64.zip -d /tmp/jre
        mkdir -p runtime
        mv /tmp/jre/*/* runtime
        cp target/profedit.jar ./
        mv target/profedit.exe ./
        zip -r bundle.zip runtime profedit.jar profedit.exe

    - name: Set enviroment for github-release
      run: |
        echo RELEASE_TAG="$(grep -m1 'defproject' project.clj | awk '{print $3}' | tr -d '\"')" >> "$GITHUB_ENV"
        echo RELEASE_NAME="$GITHUB_WORKFLOW" >> "$GITHUB_ENV"

    - name: Create a Release
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.RELEASE_TAG }}
        gzip: false
        files: >
          bundle.zip
          target/profedit.jar
        allow_override: true
